# 9. 常用内置功能

## 内置fixture

### capfd

用于拦截命令行的输出



```python
def test_system_echo(capfd):
    os.system('echo "hello"')
    captured = capfd.readouterr()
    assert captured.out == "hello\n"
```



### [caplog](https://docs.pytest.org/en/7.4.x/reference/reference.html#id33)

拦截日志信息, 返回一个LogCaptureFixture对象, 通过内置的属性获取具体信息

```bash
* caplog.messages        -> list of format-interpolated log messages
* caplog.text            -> string containing formatted log output
* caplog.records         -> list of logging.LogRecord instances
* caplog.record_tuples   -> list of (logger_name, level, message) tuples
* caplog.clear()         -> clear captured records and formatted log output string
```

### [capsys](https://docs.pytest.org/en/7.4.x/reference/reference.html#id34)

与`capfd`功能类似, 同样用于拦截命令行输出

```python
def test_output(capsys):
    print("hello")
    captured = capsys.readouterr()
    assert captured.out == "hello\n"
```

### [request](https://docs.pytest.org/en/7.4.x/reference/reference.html#id44)

特殊的内置方法, 保存了调用测试用例的请求信息.



## 内置方法

### [pytest.importorskip](https://docs.pytest.org/en/7.4.x/reference/reference.html#id11)

导入指定的模块, 如果导入失败则跳过当前测试模块

```python
docutils = pytest.importorskip("docutils")
```

### [pytest.raises](https://docs.pytest.org/en/7.4.x/reference/reference.html#id16)

期望抛出指定的异常, 如果抛出则运行通过, 否则失败

```python
def test_raises_exception():
    with pytest.raises(ValueError) as exc_info:
        raise ValueError("message")

    assert exc_info.type is ValueError
    assert exc_info.value.args[0] == 'message'
```
